Fix tests that require sasl on docker
CentOS only supports glibc 2.12 but the sasl import was failing with:
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/rh/python27/root/usr/lib64/python2.7/site-packages/_saslwrapper.so)

To do this, the pip install command had to link to our Mozilla repo. This is better anyway since PyPI can go down and also poses some security concerns.

This patch also adds `&& yum clean` which saves a surprising amount of disk space in the image.