Fix unicode error on copying over extracted files from zip.
Refs #3579

The problem here is that under very hard unit-testable/reproducable
circumstances a zip-file with unicode filenames get's extracted to a
temporary directory and while calling `copy_over` which calls
`shutil.copytree` which fails on our production systems with a
UnicodeDecodeError.

Reproducing this is something along the lines of

>>> shutil.copytree(u'/tmp/tmp8WG6A8/', u'/tmp/tmp8WG6A8-2/')
shutil.copytree('/tmp/tmp8WG6A8/', u'/tmp/tmp8WG6A8-2/')
UnicodeDecodeError: 'ascii' codec can't decode 	byte 0xd0 in ...

Checking all relevant environment configs in our production systems, all
LANG, LC_ALL and related configs are perfectly fine. It's not related to
uwsgi, it's not related to EFS so it's something else I have absolutely
no idea about :-/