Revert "Make user average_addon_rating in the API a float (as documented)"
This reverts commit 98fbdcf6ce71832abf20387adc3f3bb934fb43a0.

It was causing https://sentry.prod.mozaws.net/operations/olympia-prod/issues/3365259/

ValueError: could not convert string to float:

Because the model field is actually still a CharField, which can contain
an empty string, at least for some accounts :(